### ISSUE TITLE
The 'spark-history' service fails when building a local universe

### ISSUE THREAD

**Issue by jcmcken** [mesosphere/universe#1092]
The ``scripts/local-universe.py`` script fails when it hits ``spark-history``. Traceback:

```
Traceback (most recent call last):
  File "./scripts/local-universe.py", line 369, in <module>
    sys.exit(main())
  File "./scripts/local-universe.py", line 131, in main
    args.selected)):
  File "/usr/lib64/python3.4/concurrent/futures/_base.py", line 549, in result_iterator
    yield future.result()
  File "/usr/lib64/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/usr/lib64/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib64/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./scripts/local-universe.py", line 108, in handle_package
    args.nonlocal_cli,
  File "./scripts/local-universe.py", line 291, in prepare_repository
    with source_resource.open(encoding='utf-8') as source_file, \
  File "/usr/lib64/python3.4/pathlib.py", line 1086, in open
    opener=self._opener)
  File "/usr/lib64/python3.4/pathlib.py", line 960, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib64/python3.4/pathlib.py", line 326, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'repo/packages/S/spark-history/0/resource.json'
```

**Comment by narendrar-egnaroinc** [comment]
This make not sense, but to go for the next step just skip the **spark-history** or else we need to have resource.json  file to install.
