### ISSUE TITLE
can't launch a kafka service in dcos 1.9

### ISSUE THREAD

**Issue by eurekao** [mesosphere/universe#1184]
- when i use confluent-kafka 1.1.19.1-3.2.0e,the broker-0 can't startup it show this:
```
kafka.common.KafkaException: Unable to parse PLAINTEXT:///opt/mesosphere/bin/detect_ip: line 4: ip: command not found:0 to a broker endpoint
	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:50)
	at kafka.utils.CoreUtils$$anonfun$listenerListToEndPoints$1.apply(CoreUtils.scala:281)
	at kafka.utils.CoreUtils$$anonfun$listenerListToEndPoints$1.apply(CoreUtils.scala:281)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:281)
	at kafka.server.KafkaConfig.getAdvertisedListeners(KafkaConfig.scala:1028)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:967)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:779)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:776)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:58)
	at kafka.Kafka.main(Kafka.scala)
```
- when i use kafka 1.1.19.1-0.10.1.0 is the same as confluent-kafka 1.1.19.1-3.2.0e
- when i use beta-kafka 1.1.22-0.10.1.0-beta,it will show this error:
```
Exception in thread "main" com.mesosphere.sdk.kafka.upgrade.KafkaConfigUpgrade$KafkaConfigUpgradeException: Aborting Kafka Configuration Upgrade !!!
	at com.mesosphere.sdk.kafka.upgrade.KafkaConfigUpgrade.startUpgrade(KafkaConfigUpgrade.java:75)
	at com.mesosphere.sdk.kafka.upgrade.KafkaConfigUpgrade.<init>(KafkaConfigUpgrade.java:58)
	at com.mesosphere.sdk.kafka.scheduler.KafkaService.<init>(KafkaService.java:35)
	at com.mesosphere.sdk.kafka.scheduler.Main.main(Main.java:16)
```
and 
```
ERROR 2017-05-24 10:31:10,513 [main] com.mesosphere.sdk.kafka.upgrade.KafkaConfigUpgrade:verifyOldTasks(132): Task broker-2 target configuration does not match with target : e505fed9-1141-49e1-bb3a-aeeae03ec4f1
```

**Comment by cruhland** [comment]
@eurekao please ask for help on the [DC/OS Community Slack](http://chat.dcos.io/) first. If it's determined that the problem is with Universe specifically, create a new issue here with the relevant details. Thanks!
