### ISSUE TITLE
Previously working universe build now fails as jsonschema==2.6.0 is not found

### ISSUE THREAD

**Issue by ChiralMedia** [mesosphere/universe#1816]
In the last couple of weeks our universe build (on a Mac) has stopped working, a git clone to a new directory and to a new Centos7 machine fail with the same error.

$ ./build.sh
Building the universe!
Downloading/unpacking jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
Cleaning up...
No distributions at all found for jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
Storing debug log for failure in /Users/CM/.pip/pip.log

-------
Curl of address shows:
$ curl https://pypi.python.org/simple
<html><head><title>301 Moved Permanently</title></head><body><center><h1>301 Moved Permanently</h1></center></body></html>

-------
Content of /Users/CM/.pip/pip.log

/T/uni3/universe/scripts/../target/venv/bin/pip run on Sun Apr 22 18:08:37 2018
Downloading/unpacking jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
  Getting page https://pypi.python.org/simple/jsonschema/
  Could not fetch URL https://pypi.python.org/simple/jsonschema/: connection error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:598)
  Will skip URL https://pypi.python.org/simple/jsonschema/ when looking for download links for jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
  Getting page https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/ (Caused by <class 'http.client.CannotSendRequest'>: Request-sent)
  Will skip URL https://pypi.python.org/simple/ when looking for download links for jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
  Cannot fetch index base URL https://pypi.python.org/simple/
  URLs to search for versions for jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1)):
  * https://pypi.python.org/simple/jsonschema/2.6.0
  * https://pypi.python.org/simple/jsonschema/
  Getting page https://pypi.python.org/simple/jsonschema/2.6.0
  Could not fetch URL https://pypi.python.org/simple/jsonschema/2.6.0: connection error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:598)
  Will skip URL https://pypi.python.org/simple/jsonschema/2.6.0 when looking for download links for jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
  Getting page https://pypi.python.org/simple/jsonschema/
  Could not fetch URL https://pypi.python.org/simple/jsonschema/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/jsonschema/ (Caused by <class 'http.client.CannotSendRequest'>: Request-sent)
  Will skip URL https://pypi.python.org/simple/jsonschema/ when looking for download links for jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
  Could not find any downloads that satisfy the requirement jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
Cleaning up...
  Removing temporary dir /T/uni3/universe/target/venv/build...
No distributions at all found for jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))
Exception information:
Traceback (most recent call last):
  File "/T/uni3/universe/target/venv/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/T/uni3/universe/target/venv/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/T/uni3/universe/target/venv/lib/python3.4/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/T/uni3/universe/target/venv/lib/python3.4/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for jsonschema==2.6.0 (from -r /T/uni3/universe/scripts/requirements/requirements.txt (line 1))

**Comment by ChiralMedia** [comment]
Running the code manually shows the issue to be TLS related, that is that pip no longer supports earlier versions of TLS, this link https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version contains some useful ideas but updates to OpenSSL (now v1.0.2) and pip (now 10.0.1) make no difference. Still working on it…

Running:

/T/universe2/universe/scripts/../target/venv/bin/pip -v install -r /T/universe2/universe/scripts/requirements/requirements.txt

Results in:

Downloading/unpacking jsonschema==2.6.0 (from -r /T/universe2/universe/scripts/requirements/requirements.txt (line 1))

  Could not fetch URL https://pypi.python.org/simple/jsonschema/: connection error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:598)
  Will skip URL https://pypi.python.org/simple/jsonschema/ when looking for download links for jsonschema==2.6.0 (from -r /T/universe2/universe/scripts/requirements/requirements.txt (line 1))
  Could not fetch URL https://pypi.python.org/simple/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/ (Caused by <class 'http.client.CannotSendRequest'>: Request-sent)
  Will skip URL https://pypi.python.org/simple/ when looking for download links for jsonschema==2.6.0 (from -r /T/universe2/universe/scripts/requirements/requirements.txt (line 1))
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/jsonschema/2.6.0: connection error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:598)
  Will skip URL https://pypi.python.org/simple/jsonschema/2.6.0 when looking for download links for jsonschema==2.6.0 (from -r /T/universe2/universe/scripts/requirements/requirements.txt (line 1))
  Could not fetch URL https://pypi.python.org/simple/jsonschema/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/jsonschema/ (Caused by <class 'http.client.CannotSendRequest'>: Request-sent)
  Will skip URL https://pypi.python.org/simple/jsonschema/ when looking for download links for jsonschema==2.6.0 (from -r /T/universe2/universe/scripts/requirements/requirements.txt (line 1))
  Could not find any downloads that satisfy the requirement jsonschema==2.6.0 (from -r /T/universe2/universe/scripts/requirements/requirements.txt (line 1))
Cleaning up...
  Removing temporary dir /T/universe2/universe/target/venv/build...
No distributions at all found for jsonschema==2.6.0 (from -r /T/universe2/universe/scripts/requirements/requirements.txt (line 1))
Exception information:
Traceback (most recent call last):
  File "/T/universe2/universe/target/venv/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/T/universe2/universe/target/venv/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/T/universe2/universe/target/venv/lib/python3.4/site-packages/pip/req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/T/universe2/universe/target/venv/lib/python3.4/site-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for jsonschema==2.6.0 (from -r /T/universe2/universe/scripts/requirements/requirements.txt (line 1))

**Comment by ChiralMedia** [comment]
Resolved by installing latest Centos7 and reinstalling all the required tools. It appears that the old server had a dependency issue, although it also had the latest tool set to build the universe.

Please close this case.
