### ISSUE TITLE
kafka/30 seems broken

### ISSUE THREAD

**Issue by marcinjedyk-msm** [mesosphere/universe#667]
Latest Kafka from Universe (https://github.com/mesosphere/universe/tree/version-3.x/repo/packages/K/kafka/30) seems broken - when DCOS tries to provision, it erros:
Exception in thread "main" org.apache.mesos.config.ConfigStoreException: org.apache.mesos.config.ConfigStoreException: Failed to retrieve or deserialize configuration '41661307-527d-4cf8-a6fb-95c5b5dc67d6' from path '/dcos-service-kafka/Configurations/41661307-527d-4cf8-a6fb-95c5b5dc67d6'
at com.mesosphere.dcos.kafka.config.KafkaConfigState.fetch(KafkaConfigState.java:61)
at com.mesosphere.dcos.kafka.config.KafkaConfigState.getTargetConfig(KafkaConfigState.java:95)
at com.mesosphere.dcos.kafka.config.ConfigStateUpdater.getTargetConfig(ConfigStateUpdater.java:46)
at com.mesosphere.dcos.kafka.scheduler.KafkaScheduler.<init>(KafkaScheduler.java:85)
at com.mesosphere.dcos.kafka.scheduler.Main.run(Main.java:80)
at com.mesosphere.dcos.kafka.scheduler.Main.run(Main.java:32)
at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:40)
at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
at io.dropwizard.cli.Cli.run(Cli.java:70)
at io.dropwizard.Application.run(Application.java:80)
at com.mesosphere.dcos.kafka.scheduler.Main.main(Main.java:38)
Caused by: org.apache.mesos.config.ConfigStoreException: Failed to retrieve or deserialize configuration '41661307-527d-4cf8-a6fb-95c5b5dc67d6' from path '/dcos-service-kafka/Configurations/41661307-527d-4cf8-a6fb-95c5b5dc67d6'
at org.apache.mesos.curator.CuratorConfigStore.fetch(CuratorConfigStore.java:120)
at com.mesosphere.dcos.kafka.config.KafkaConfigState.fetch(KafkaConfigState.java:58)
... 10 more
Caused by: org.apache.mesos.config.ConfigStoreException: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('!' (code 33)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
at [Source: B@4d0402b; line: 1, column: 2

**Comment by cruhland** [comment]
@gabrielhartmann would you be able to help with this?

**Comment by triclambert** [comment]
Hi there @marcinjedyk-msm, can you try the latest version, 33?
