### ISSUE TITLE
SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC when deploying local-universe

### ISSUE THREAD

**Issue by toddleo** [mesosphere/universe#971]
Hi,

I'm trying to deploy my own local-universe refering to [Installing a selected set of Universe packages](https://docs.mesosphere.com/1.8/administration/installing/deploying-a-local-dcos-universe/). However, I ran in to an issue:

```
...
Completed: zeppelin
Completed: spark
Stopping docker registry.
registry
Traceback (most recent call last):
  File "/home/todd/utils/dcos-cluster/universe/docker/local-universe/../../scripts/local-universe.py", line 347, in <module>
    sys.exit(main())
  File "/home/todd/utils/dcos-cluster/universe/docker/local-universe/../../scripts/local-universe.py", line 112, in main
    args.selected)):
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib64/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/todd/utils/dcos-cluster/universe/docker/local-universe/../../scripts/local-universe.py", line 94, in handle_package
    add_http_resource(http_artifacts, url, archive_path)
  File "/home/todd/utils/dcos-cluster/universe/docker/local-universe/../../scripts/local-universe.py", line 261, in add_http_resource
    urllib.request.urlretrieve(url, str(archive_path))
  File "/usr/lib64/python3.5/urllib/request.py", line 217, in urlretrieve
    block = fp.read(bs)
  File "/usr/lib64/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib64/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib64/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib64/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib64/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib64/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)
Makefile:18: recipe for target 'local-universe' failed
make: *** [local-universe] Error 1
```

On the other machine, the error message is a bit different:

```
Stopping docker registry.
registry
Traceback (most recent call last):
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/dcos_cluster/universe/docker/local-universe/../../scripts/local-universe.py", line 347, in <module>
    sys.exit(main())
  File "/root/dcos_cluster/universe/docker/local-universe/../../scripts/local-universe.py", line 112, in main
    args.selected)):
  File "/opt/mesosphere/lib/python3.5/site-packages/concurrent/futures/_base.py", line 580, in map
    yield future.result()
  File "/opt/mesosphere/lib/python3.5/site-packages/concurrent/futures/_base.py", line 407, in result
    return self.__get_result()
  File "/opt/mesosphere/lib/python3.5/site-packages/concurrent/futures/_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "/opt/mesosphere/lib/python3.5/site-packages/concurrent/futures/_compat.py", line 111, in reraise
    raise exc
  File "/opt/mesosphere/lib/python3.5/site-packages/concurrent/futures/thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/dcos_cluster/universe/docker/local-universe/../../scripts/local-universe.py", line 94, in handle_package
    add_http_resource(http_artifacts, url, archive_path)
  File "/root/dcos_cluster/universe/docker/local-universe/../../scripts/local-universe.py", line 261, in add_http_resource
    urllib.request.urlretrieve(url, str(archive_path))
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/mesosphere/packages/python--533ea12b9ea468de5db5bfc5cee4f28a9d9c4739/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>
make: *** [local-universe] Error 1
```

Seems to be something wrong with SSL and certificate.

**Comment by narendrar-egnaroinc** [comment]
I got the same issue. 

Here are the error stack :+1: registry

AIM:  Trying to build own universal Installer with selected package and following bellow thing https://dcos.io/docs/1.9/administering-clusters/deploying-a-local-dcos-universe/#scrollNav-2
OS: Ubuntu 14.04
docker 1.12




_**Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1125, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1163, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1121, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 951, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 886, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1260, in connect
    super().connect()
  File "/usr/lib/python3.4/http/client.py", line 863, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avirup/Downloads/dcos1/universe/docker/local-universe/../../scripts/local-universe.py", line 373, in <module>
    sys.exit(main())
  File "/home/avirup/Downloads/dcos1/universe/docker/local-universe/../../scripts/local-universe.py", line 123, in main
    args.selected)):
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 549, in result_iterator
    yield future.result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/usr/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/avirup/Downloads/dcos1/universe/docker/local-universe/../../scripts/local-universe.py", line 105, in handle_package
    add_http_resource(http_artifacts, url, archive_path)
  File "/home/avirup/Downloads/dcos1/universe/docker/local-universe/../../scripts/local-universe.py", line 279, in add_http_resource
    urllib.request.urlretrieve(url, str(archive_path))
  File "/usr/lib/python3.4/urllib/request.py", line 186, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
make: *** [local-universe] Error 1**_
